### ISSUE TITLE
vechicleinfo.py is missing information for gazebo-minihawk

### ISSUE THREAD

**Issue by notgull** [robowork/aerial_robotics#2]
This causes the simulation to fail with a `KeyError: 'gazebo'` error, as mentioned during office hours.

**Comment by notgull** [comment]
Here is the patched file: https://gist.github.com/notgull/58f2fced2ce3edc6c80a97ebdcda96c7

**Comment by papachric** [comment]
Should be addressed by commit 4fa5ddbae1b569ee388790c6ee7cfb972947e7f5
