### ISSUE TITLE
gazebo resources misplaced/missing

### ISSUE THREAD

**Issue by cap099** [robowork/aerial_robotics#4]
Gazebo can't find 2 model directories which correspond to the Office building and April tag in the simulation. The AprilTag can be found in the aerial_robotics repository under `aerial_robotics/robowork_minihawk_gazebo/models/` and needs to be moved to `/usr/share/gazebo-9/models/`  Similarly, the directory containing the office building sdf and additional textures needs to be moved to the same spot. I found a copy of the (an? might not be the exact same resource) office building at https://github.com/osrf/gazebo_models/tree/master/office_building since it didn't seem to be in the repository.

**Comment by papachric** [comment]
should be fixed by 0813fb330bfe8dafde48c64e7467bb48b1688b6e

btw you don't need to copy model resources to system folders `/usr/share/gazebo-9/models/` 
you can copy them to the local user folder `$HOME/.gazebo/models`
